### ISSUE TITLE
Actions not updating state

### ISSUE THREAD

**Issue by drejohnson** [yawaramin/re-hyperapp#1]
Hello, I've been playing around with this repo and I can't get `actions` to update `state`. I made a repo https://github.com/drejohnson/reason-hyperapp with a simple counter example.

**Comment by yawaramin** [comment]
Hi there, sorry, I've been pretty swamped for the last few months! I took a look at you code and believe this might be the culprit:

https://github.com/drejohnson/reason-hyperapp/blob/ecc3d0e554576e1f1cb8c16e03b68d12cca9f87e/src/index.re#L9

According to https://bucklescript.github.io/docs/en/object#creation :

> Since `bs.deriving abstract` turns the above person record into an abstract type, you can't directly create a person record as you would usually. This doesn't work: `{name: "Joe", age: 20, job: "teacher"}`.

It seems that what you have in your repo won't compile. However, I've now updated and reorganized this binding, including adding JSX support. Check out https://github.com/yawaramin/re-hyperapp/blob/0f958c606d7911fda4ceb18ab3e764111d2ff9b6/src/Yawaramin_ReHyperapp/Yawaramin_ReHyperapp_Demo.re for a sample application, and https://github.com/yawaramin/re-hyperapp/blob/0f958c606d7911fda4ceb18ab3e764111d2ff9b6/src/Yawaramin_ReHyperapp.re and its related modules in the project for more documentation.
